name: apples
channels:
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - ipython
  - opencv
  - pytorch
  - torchvision
  - ninja
  - onnx-caffe2
  - onnxruntime
  - pip:
      - prospector
